from datetime import datetime


def export_markdown(filepath: str, analyzer) -> None:
    p = analyzer.profile
    stats = analyzer.commit_stats
    streak = analyzer.streak_data
    langs = analyzer.languages
    repos = [r for r in analyzer.repos if not r.get("fork")][:5]

    lines = []
    lines.append(f"# GitPulse Report — @{p['login']}\n")
    lines.append(f"> Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")

    lines.append(f"## 👤 Profile\n")
    lines.append(f"- **Name:** {p['name']}\n")
    lines.append(f"- **Bio:** {p['bio']}\n")
    lines.append(f"- **Location:** {p['location']}\n")
    lines.append(f"- **Followers:** {p['followers']}  |  **Following:** {p['following']}\n")
    lines.append(f"- **Public Repos:** {p['public_repos']}\n\n")

    lines.append(f"## 💻 Languages\n")
    for lang, pct in langs.items():
        lines.append(f"- {lang}: {pct}%\n")
    lines.append("\n")

    lines.append(f"## 📦 Top Repositories\n")
    lines.append("| Repo | Stars | Forks | Language |\n")
    lines.append("|------|-------|-------|----------|\n")
    for r in repos:
        lines.append(
            f"| [{r['name']}]({r['html_url']}) | "
            f"{r.get('stargazers_count',0)} | "
            f"{r.get('forks_count',0)} | "
            f"{r.get('language') or '—'} |\n"
        )
    lines.append("\n")

    lines.append(f"## 📊 Commit Activity\n")
    lines.append(f"- Last 30 days: **{stats.get('last_30_days', 0)}** commits\n")
    lines.append(f"- Last 365 days: **{stats.get('last_365_days', 0)}** commits\n")
    lines.append(f"- Active days: **{stats.get('active_days', 0)}**\n\n")

    lines.append(f"## 🔥 Streaks\n")
    lines.append(f"- Current streak: **{streak.get('current', 0)}** days\n")
    lines.append(f"- Longest streak: **{streak.get('longest', 0)}** days\n\n")

    lines.append(f"## 🏆 Impact Score\n")
    lines.append(f"**{analyzer.impact_score} / 100**\n\n")
    lines.append(f"---\n*Generated by [gitpulse](https://github.com/yourusername/gitpulse)*\n")

    with open(filepath, "w", encoding="utf-8") as f:
        f.writelines(lines)
